#Each new term in the Fibonacci sequence is generated by adding the previous
#two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the
#Fibonacci sequence whose values do not exceed four million, find the
#sum of the even-valued terms.

fibArr = [1, 2]

result = 2

while max(fibArr) < 4000000:
    fibArr.append(fibArr[len(fibArr) - 2] + fibArr[len(fibArr) - 1])

    if fibArr[len(fibArr) - 1] % 2 == 0:
        result = result + fibArr[len(fibArr) - 1]

print result
